create table if not exists public.ott_platforms (
  id bigint generated by default as identity primary key,
  name text not null check (btrim(name) <> ''),
  logo_url text not null default '',
  website_url text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ott_platforms_name_lower_unique
  on public.ott_platforms (lower(name));
create index if not exists ott_platforms_active_name_idx
  on public.ott_platforms (is_active, name);

insert into public.ott_platforms (name, website_url)
select seed.name, seed.website_url
from (values
  ('Netflix', 'https://www.netflix.com'),
  ('Prime Video', 'https://www.primevideo.com'),
  ('JioHotstar', 'https://www.hotstar.com'),
  ('SonyLIV', 'https://www.sonyliv.com'),
  ('ZEE5', 'https://www.zee5.com'),
  ('Apple TV+', 'https://tv.apple.com'),
  ('YouTube', 'https://www.youtube.com')
) as seed(name, website_url)
where not exists (
  select 1 from public.ott_platforms existing
  where lower(existing.name) = lower(seed.name)
);

alter table public.ott_platforms enable row level security;

drop policy if exists "Anyone can view enabled OTT platforms" on public.ott_platforms;
create policy "Anyone can view enabled OTT platforms"
  on public.ott_platforms for select to anon, authenticated
  using (is_active or public.is_admin());

drop policy if exists "Admins can insert OTT platforms" on public.ott_platforms;
create policy "Admins can insert OTT platforms"
  on public.ott_platforms for insert to authenticated
  with check (public.is_admin());

drop policy if exists "Admins can update OTT platforms" on public.ott_platforms;
create policy "Admins can update OTT platforms"
  on public.ott_platforms for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can delete OTT platforms" on public.ott_platforms;
create policy "Admins can delete OTT platforms"
  on public.ott_platforms for delete to authenticated
  using (public.is_admin());

grant select on public.ott_platforms to anon, authenticated;
grant insert, update, delete on public.ott_platforms to authenticated;
grant usage, select on sequence public.ott_platforms_id_seq to authenticated;

notify pgrst, 'reload schema';
