create table if not exists public.tv_shows (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null default '',
  keywords text[] not null default '{}',
  tags text[] not null default '{}',
  meta_description text not null default '',
  title_image_url text not null default '',
  original_title text not null default '',
  premiere_date date,
  end_date date,
  show_status text not null default 'Upcoming'
    check (show_status in ('Upcoming', 'Ongoing', 'Completed', 'Cancelled', 'On Hiatus')),
  country text not null default '',
  age_rating text not null default '',
  languages text[] not null default '{}',
  production_company text not null default '',
  network text not null default '',
  number_of_seasons integer not null default 0 check (number_of_seasons >= 0),
  total_episodes integer not null default 0 check (total_episodes >= 0),
  episodes_per_season integer[] not null default '{}',
  average_episode_runtime integer not null default 0 check (average_episode_runtime >= 0),
  episode_release_schedule text not null default 'Other',
  first_air_date date,
  last_air_date date,
  current_season integer not null default 0 check (current_season >= 0),
  current_episode integer not null default 0 check (current_episode >= 0),
  series_type text not null default 'TV Series'
    check (series_type in ('TV Series', 'Web Series', 'Mini-Series', 'Limited Series', 'Anthology')),
  genres text[] not null default '{}',
  tagline text not null default '',
  short_description text not null default '',
  description text not null default '',
  story text not null default '',
  season_overview text not null default '',
  poster_url text not null default '',
  backdrop_url text not null default '',
  banner_url text not null default '',
  thumbnail_url text not null default '',
  trailer_url text not null default '',
  teaser_url text not null default '',
  watch_providers jsonb not null default '[]'::jsonb,
  tmdb_rating numeric(3,1) check (tmdb_rating is null or tmdb_rating between 0 and 10),
  imdb_rating numeric(3,1) check (imdb_rating is null or imdb_rating between 0 and 10),
  user_rating numeric(3,1) check (user_rating is null or user_rating between 0 and 10),
  vote_count integer not null default 0 check (vote_count >= 0),
  popularity numeric(12,3) not null default 0,
  initial_hype numeric(5,2) check (initial_hype is null or initial_hype between 0 and 100),
  is_trending boolean not null default false,
  is_popular boolean not null default false,
  is_rising boolean not null default false,
  is_new boolean not null default false,
  is_top_rated boolean not null default false,
  editors_pick boolean not null default false,
  badges text[] not null default '{}',
  is_published boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tv_shows add column if not exists slug text not null default '';
alter table public.tv_shows add column if not exists keywords text[] not null default '{}';
alter table public.tv_shows add column if not exists tags text[] not null default '{}';
alter table public.tv_shows add column if not exists meta_description text not null default '';

create index if not exists tv_shows_published_created_idx
  on public.tv_shows (is_published, created_at desc);
create index if not exists tv_shows_genres_idx on public.tv_shows using gin (genres);
create index if not exists tv_shows_languages_idx on public.tv_shows using gin (languages);

create table if not exists public.tv_show_seasons (
  id bigint generated by default as identity primary key,
  tv_show_id bigint not null references public.tv_shows(id) on delete cascade,
  season_number integer not null check (season_number >= 0),
  title text not null default '',
  overview text not null default '',
  poster_url text not null default '',
  release_date date,
  episode_count integer not null default 0 check (episode_count >= 0),
  status text not null default 'Upcoming',
  display_order integer not null default 0,
  unique (tv_show_id, season_number)
);
create index if not exists tv_show_seasons_order_idx
  on public.tv_show_seasons (tv_show_id, display_order);

create table if not exists public.tv_show_episodes (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.tv_show_seasons(id) on delete cascade,
  episode_number integer not null check (episode_number >= 0),
  title text not null default '',
  overview text not null default '',
  air_date date,
  runtime integer not null default 0 check (runtime >= 0),
  still_url text not null default '',
  trailer_url text not null default '',
  rating numeric(3,1) check (rating is null or rating between 0 and 10),
  status text not null default 'Upcoming',
  director text not null default '',
  writer text not null default '',
  display_order integer not null default 0,
  unique (season_id, episode_number)
);
create index if not exists tv_show_episodes_order_idx
  on public.tv_show_episodes (season_id, display_order);

create table if not exists public.tv_show_cast (
  id bigint generated by default as identity primary key,
  tv_show_id bigint not null references public.tv_shows(id) on delete cascade,
  cast_member_id uuid not null references public.cast_members(id) on delete cascade,
  character_name text not null default '',
  cast_order integer not null default 0,
  unique (tv_show_id, cast_member_id)
);
create index if not exists tv_show_cast_member_idx on public.tv_show_cast (cast_member_id);

create table if not exists public.tv_show_crew (
  id bigint generated by default as identity primary key,
  tv_show_id bigint not null references public.tv_shows(id) on delete cascade,
  person_name text not null,
  department text not null default 'Other',
  job text not null default '',
  image_url text not null default '',
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists tv_show_crew_order_idx on public.tv_show_crew (tv_show_id, display_order);

alter table public.tv_shows enable row level security;
alter table public.tv_show_seasons enable row level security;
alter table public.tv_show_episodes enable row level security;
alter table public.tv_show_cast enable row level security;
alter table public.tv_show_crew enable row level security;

drop policy if exists "Anyone can view published TV shows" on public.tv_shows;
create policy "Anyone can view published TV shows"
  on public.tv_shows for select to anon, authenticated
  using (is_published or public.is_admin());
drop policy if exists "Admins can insert TV shows" on public.tv_shows;
create policy "Admins can insert TV shows"
  on public.tv_shows for insert to authenticated
  with check (public.is_admin() and (created_by is null or created_by = auth.uid()));
drop policy if exists "Admins can update TV shows" on public.tv_shows;
create policy "Admins can update TV shows"
  on public.tv_shows for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins can delete TV shows" on public.tv_shows;
create policy "Admins can delete TV shows"
  on public.tv_shows for delete to authenticated using (public.is_admin());

drop policy if exists "Anyone can view published TV show seasons" on public.tv_show_seasons;
create policy "Anyone can view published TV show seasons"
  on public.tv_show_seasons for select to anon, authenticated
  using (exists (
    select 1 from public.tv_shows s
    where s.id = tv_show_id and (s.is_published or public.is_admin())
  ));
drop policy if exists "Admins can manage TV show seasons" on public.tv_show_seasons;
create policy "Admins can manage TV show seasons"
  on public.tv_show_seasons for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Anyone can view published TV show episodes" on public.tv_show_episodes;
create policy "Anyone can view published TV show episodes"
  on public.tv_show_episodes for select to anon, authenticated
  using (exists (
    select 1 from public.tv_show_seasons s
    join public.tv_shows t on t.id = s.tv_show_id
    where s.id = season_id and (t.is_published or public.is_admin())
  ));
drop policy if exists "Admins can manage TV show episodes" on public.tv_show_episodes;
create policy "Admins can manage TV show episodes"
  on public.tv_show_episodes for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Anyone can view published TV show cast" on public.tv_show_cast;
create policy "Anyone can view published TV show cast"
  on public.tv_show_cast for select to anon, authenticated
  using (exists (
    select 1 from public.tv_shows s
    where s.id = tv_show_id and (s.is_published or public.is_admin())
  ));
drop policy if exists "Admins can manage TV show cast" on public.tv_show_cast;
create policy "Admins can manage TV show cast"
  on public.tv_show_cast for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Anyone can view published TV show crew" on public.tv_show_crew;
create policy "Anyone can view published TV show crew"
  on public.tv_show_crew for select to anon, authenticated
  using (exists (
    select 1 from public.tv_shows s
    where s.id = tv_show_id and (s.is_published or public.is_admin())
  ));
drop policy if exists "Admins can manage TV show crew" on public.tv_show_crew;
create policy "Admins can manage TV show crew"
  on public.tv_show_crew for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

grant select on public.tv_shows, public.tv_show_seasons, public.tv_show_episodes,
  public.tv_show_cast, public.tv_show_crew to anon, authenticated;
grant insert, update, delete on public.tv_shows, public.tv_show_seasons,
  public.tv_show_episodes, public.tv_show_cast, public.tv_show_crew to authenticated;
grant usage, select on sequence public.tv_shows_id_seq,
  public.tv_show_seasons_id_seq,
  public.tv_show_episodes_id_seq,
  public.tv_show_cast_id_seq,
  public.tv_show_crew_id_seq to authenticated;

create or replace function public.save_tv_show_seasons(p_tv_show_id bigint, p_seasons jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  season_data jsonb;
  episode_data jsonb;
  saved_season_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Only admins can save TV show seasons.';
  end if;

  delete from public.tv_show_seasons where tv_show_id = p_tv_show_id;
  for season_data in select value from jsonb_array_elements(coalesce(p_seasons, '[]'::jsonb))
  loop
    insert into public.tv_show_seasons (
      tv_show_id, season_number, title, overview, poster_url, release_date,
      episode_count, status, display_order
    ) values (
      p_tv_show_id,
      (season_data->>'season_number')::integer,
      coalesce(season_data->>'title', ''),
      coalesce(season_data->>'overview', ''),
      coalesce(season_data->>'poster_url', ''),
      nullif(season_data->>'release_date', '')::date,
      jsonb_array_length(coalesce(season_data->'episodes', '[]'::jsonb)),
      coalesce(season_data->>'status', 'Upcoming'),
      coalesce((season_data->>'display_order')::integer, 0)
    ) returning id into saved_season_id;

    for episode_data in select value from jsonb_array_elements(coalesce(season_data->'episodes', '[]'::jsonb))
    loop
      insert into public.tv_show_episodes (
        season_id, episode_number, title, overview, air_date, runtime, still_url,
        trailer_url, rating, status, director, writer, display_order
      ) values (
        saved_season_id,
        (episode_data->>'episode_number')::integer,
        coalesce(episode_data->>'title', ''),
        coalesce(episode_data->>'overview', ''),
        nullif(episode_data->>'air_date', '')::date,
        coalesce(nullif(episode_data->>'runtime', '')::integer, 0),
        coalesce(episode_data->>'still_url', ''),
        coalesce(episode_data->>'trailer_url', ''),
        nullif(episode_data->>'rating', '')::numeric,
        coalesce(episode_data->>'status', 'Upcoming'),
        coalesce(episode_data->>'director', ''),
        coalesce(episode_data->>'writer', ''),
        coalesce((episode_data->>'display_order')::integer, 0)
      );
    end loop;
  end loop;

end;
$$;

create or replace function public.save_tv_show_cast(p_tv_show_id bigint, p_cast jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can save TV show cast.';
  end if;

  delete from public.tv_show_cast where tv_show_id = p_tv_show_id;
  insert into public.tv_show_cast (tv_show_id, cast_member_id, character_name, cast_order)
  select
    p_tv_show_id,
    (value->>'cast_member_id')::uuid,
    coalesce(value->>'character_name', ''),
    coalesce((value->>'cast_order')::integer, 0)
  from jsonb_array_elements(coalesce(p_cast, '[]'::jsonb));
end;
$$;

grant execute on function public.save_tv_show_seasons(bigint, jsonb) to authenticated;
grant execute on function public.save_tv_show_cast(bigint, jsonb) to authenticated;

drop policy if exists "Admins can upload cast crew profile images" on storage.objects;
create policy "Admins can upload cast crew profile images"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'POSTER' and public.is_admin());
drop policy if exists "Admins can delete cast crew profile images" on storage.objects;
create policy "Admins can delete cast crew profile images"
  on storage.objects for delete to authenticated
  using (bucket_id = 'POSTER' and public.is_admin());
