create table if not exists public.hero_tv_shows (
  id bigint generated by default as identity primary key,
  tv_show_id bigint not null unique references public.tv_shows(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.hero_tv_shows enable row level security;

drop policy if exists "Anyone can view TV show hero entries" on public.hero_tv_shows;
create policy "Anyone can view TV show hero entries"
  on public.hero_tv_shows for select
  to anon, authenticated
  using (true);

drop policy if exists "Admins can insert TV show hero entries" on public.hero_tv_shows;
create policy "Admins can insert TV show hero entries"
  on public.hero_tv_shows for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "Admins can update TV show hero entries" on public.hero_tv_shows;
create policy "Admins can update TV show hero entries"
  on public.hero_tv_shows for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can delete TV show hero entries" on public.hero_tv_shows;
create policy "Admins can delete TV show hero entries"
  on public.hero_tv_shows for delete
  to authenticated
  using (public.is_admin());

create index if not exists hero_tv_shows_position_idx on public.hero_tv_shows (position);

grant select on public.hero_tv_shows to anon, authenticated;
grant insert, update, delete on public.hero_tv_shows to authenticated;
grant usage, select on sequence public.hero_tv_shows_id_seq to authenticated;
